disable broken tests
They require non-existent piece of code:

 1/30 Test #29: py-eg-talos_warm_start .................***Failed    0.24 sec
Traceback (most recent call last):
  File "/home/gsaurel/local/loco-3d/crocoddyl/examples/locomotion/talos_warm_start.py", line 7, in <module>
    from crocoddyl.locomotion import (ContactSequenceHumanoid, createMultiphaseShootingProblem,
  File "/home/gsaurel/local/loco-3d/crocoddyl/crocoddyl/locomotion/__init__.py", line 10, in <module>
    from crocoddyl.locomotion import CubicHermiteSpline
ImportError: cannot import name CubicHermiteSpline

11/30 Test #11: py-locomotion ..........................***Failed    0.60 sec
Traceback (most recent call last):
  File "/home/gsaurel/local/loco-3d/crocoddyl/unittest/test_locomotion.py", line 3, in <module>
    from crocoddyl.locomotion import ContactSequenceHumanoid, createPhiFromContactSequence
  File "/home/gsaurel/local/loco-3d/crocoddyl/crocoddyl/locomotion/__init__.py", line 10, in <module>
    from crocoddyl.locomotion import CubicHermiteSpline
ImportError: cannot import name CubicHermiteSpline